name: Run Develocity Connectivity Report

on:
  schedule:
    # Every Sunday at 9.00am
    - cron: "0 9 * * 0"

  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run
        run: ./gradlew run -PagreeToGradleTermsOfService=yes
        env:
          GITHUB_API_KEY: ${{ secrets.GH_API_KEY }}
